services:
  chatgpt-next-web:
    container_name: chatgpt-next-web
    image: nguyenvulong/nextchat-slim:latest
    build:
      context: .
      platforms:
        - linux/amd64
        - linux/arm64
    platform: linux/${ARCH:-$(uname -m | sed 's/x86_64/amd64/' | sed 's/aarch64/arm64/')}
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: unless-stopped