services:
  chatgpt-next-web:
    container_name: chatgpt-next-web
    image: nguyenvulong/nextchat-slim
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile.${PLATFORM:-amd64}
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    restart: unless-stopped