services:
  next-web:
    container_name: next-web
    image: docker.io/nguyenvulong/nextchat-slim:latest
    ports:
      - 3000:3000
    networks:
      - next-chat-network
    env_file:
      - .env

networks:
  next-chat-network:
    driver: bridge
    name: next-chat-network